### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ksmack** [mike-ward/tweetz-desktop#5]
---------------------------

---------------------------
Tweetz Desktop Crash Report

Date: 2015-09-04 19:34:28Z

Version: 0.8.23

-----------------------------------------------------------------

*** Pressing Ctrl+C will copy the contents of this dialog ***

*** Email to: mike@mike-ward.net ***

-----------------------------------------------------------------

Operation System Information

-----------------------------------------------------------------

Windows 7 Enterprise

Service Pack: Service Pack 1

Exception

-----------------------------------------------------------------

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.

Parameter name: length

   at System.String.Substring(Int32 startIndex, Int32 length)

   at tweetz5.Model.TweetUtilities.BuildMarkupNodes(String text, Entities entities) in c:\Users\Mike\Documents\GitHub\tweetz-desktop\tweetz\tweetz5\Model\TweetUtilities.cs:line 132

   at tweetz5.Model.TweetUtilities.CreateTweet(Status status, TweetClassification tweetType) in c:\Users\Mike\Documents\GitHub\tweetz-desktop\tweetz\tweetz5\Model\TweetUtilities.cs:line 35

   at tweetz5.Model.Timelines.UpdateTimelines(IEnumerable`1 statuses, TweetClassification tweetType) in c:\Users\Mike\Documents\GitHub\tweetz-desktop\tweetz\tweetz5\Model\Timelines.cs:line 29

   at tweetz5.Model.Timelines.<>c__DisplayClass1.<UpdateStatus>b__0() in c:\Users\Mike\Documents\GitHub\tweetz-desktop\tweetz\tweetz5\Model\Timelines.cs:line 57

   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   --- End of inner exception stack trace ---

---> (Inner Exception #0) System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.

Parameter name: length

   at System.String.Substring(Int32 startIndex, Int32 length)

   at tweetz5.Model.TweetUtilities.BuildMarkupNodes(String text, Entities entities) in c:\Users\Mike\Documents\GitHub\tweetz-desktop\tweetz\tweetz5\Model\TweetUtilities.cs:line 132

   at tweetz5.Model.TweetUtilities.CreateTweet(Status status, TweetClassification tweetType) in c:\Users\Mike\Documents\GitHub\tweetz-desktop\tweetz\tweetz5\Model\TweetUtilities.cs:line 35

   at tweetz5.Model.Timelines.UpdateTimelines(IEnumerable`1 statuses, TweetClassification tweetType) in c:\Users\Mike\Documents\GitHub\tweetz-desktop\tweetz\tweetz5\Model\Timelines.cs:line 29

   at tweetz5.Model.Timelines.<>c__DisplayClass1.<UpdateStatus>b__0() in c:\Users\Mike\Documents\GitHub\tweetz-desktop\tweetz\tweetz5\Model\Timelines.cs:line 57

   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()<---

---------------------------
OK   
---------------------------

**Comment by ksmack** [comment]
I had this issue happen on a previous version as well. I assume it is conflicting with a windows update possibly since it just started out of the blue.
